name: "Openapi Generator"
description: "Generates some Libraries based of open api file"
inputs:
  SCHEMA_FILE_PATH:
    description: "Path to openapi file"
    required: true
    default: "api.yml"
  DEPLOY_TOKEN:
    description: "Your deploy token"
    required: true
runs:
  using: node12
  main: "lib/main.js"
