openapi: 3.0.0
info:
  title: JSON Placeholder OpenAPI
  description: Example spec of the well known JSON Placeholder website
  version: 0.1.15
tags:
  - name: qr
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /code/qr/edit/{serialNumber}:
    post:
      tags:
        - qr
      summary: Edit QR Code and returns Base Data
      operationId: editQRCode
      parameters:
        - in: path
          required: true
          name: serialNumber
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QRCodeCreateData'
      responses:
        200:
          description: Successfully edited QR Code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCodeBaseData'

  /code/qr/create:
    post:
      tags:
        - qr
      summary: Creates a new QR Code and returns Base Data
      operationId: createQRCode
      requestBody:
        required: true
        description: QR Code Data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QRCodeCreateData'
      responses:
        200:
          description: Successfuly created QR Code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCodeBaseData'

  /code/qr/{serialNumber}:
    get:
      tags:
        - qr
      summary: Gets Qr Code image and base Data
      operationId: getQRCode
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successfuly found QR code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCodeBaseData'

  /code/qr/deactivate/{serialNumber}:
    post:
      summary: Deactivate QR Code Code
      operationId: deactivateQRCode
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successfully deactivate QR Code

components:
  schemas:
    QRCodeBaseData:
      type: object
      required:
        - serialNumber
        - url
        - image
      properties:
        serialNumber:
          type: string
          format: uuid
        url:
          type: string
        image:
          type: string
          format: binary
    QRCodeCreateData:
      type: object
      required:
        - url
      properties:
        url:
          type: string
        styleData:
          $ref: '#/components/schemas/QRCodeStyleData'
    QRCodeStyleData:
      type: object
      properties:
        fileName:
          type: string
          description: Name of QR Code image file
          default: QRcode.png
        size:
          type: integer
          description: Size of QR Code in Pixel
          default: 25
        margin:
          type: integer
          description: Amount of space in pixels to add as a margin around the rendered QR Code
          default: 0
        brightColor:
          type: string
          description: Color to be used for the "bright" parts of the QR Code. As HEX string
          default: #FFFFFF
        darkColor:
          type: string
          description: Color to be used for the "dark" parts of the QR Code. As HEX string
          default: #000000
        marginColor:
          type: string
          description: Color to be used for the "margin" part of the QR Code. As HEX string
          default: #FFFFFF
